name: BotInversor7Sabios
on:
  schedule:
    - cron: '0 9 * * *' # Se ejecuta a las 9 AM UTC
  workflow_dispatch: # Permite que tú le des al botón de "Ejecutar ahora"

jobs:
  run-bot:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Permiso crucial para que el bot guarde sus archivos de memoria
    steps:
      - name: Checkout código
        uses: actions/checkout@v3
      
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Instalar dependencias
        run: pip install requests beautifulsoup4
      
      - name: Ejecutar Bot
        run: python bot.py
      
      - name: Guardar estados de carteras
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add *.txt
          git commit -m "Actualización diaria de carteras" || exit 0
          git push
