name: Buffett Tracker
on:
  schedule:
    - cron: '0 10 * * *'  # Esto lo ejecuta a las 10:00 AM UTC (ajusta a tu gusto)
  workflow_dispatch:      # Esto te permite darle al botón "Play" manual en GitHub

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3
      
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Instalar librerías
        run: pip install -r requirements.txt
        
      - name: Ejecutar Bot
        run: python bot.py
        
      - name: Guardar cambios en la base de datos local
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add cartera.txt
          git commit -m "Actualizar base de datos" || echo "Sin cambios"
          git push
          
